version: '3.8'

services:
  monorepo_sandbox_frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
